name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull sandeshjain/mlproject:latest
    - name: Delete Old docker container
      run: sudo docker rm -f mlproject-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8501:8501 --name mlproject-container sandeshjain/mlproject